name: Test and run 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - development

  pull_request:
    branches:
    - development
  
env:
    PG_CONN: ${{ secrets.PG_CONN }}
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Export variable
        run: |
          export pgconn=${{ secrets.PG_CONN }}
           
      - uses: actions/checkout@v4
   
      - name: Install dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build
        
      - name: Test with the dotnet CLI
        run: dotnet test   
     
             
      
  Deploy-Preview:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Set Up PostgreSQL
        run: |
          export pgconn=${{ secrets.PG_CONN }}

      - name: Build and Deploy
        run: dotnet build --configuration Release --no-restore


