name: Test and run 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - development

  pull_request:
    branches:
    - development
  
env:
    PG_CONN: ${{ secrets.PG_CONN }}
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
           
      - name: Start API Server and test
        run: |
          cd scripts
          chmod +x ./wait-for-it.sh
          dotnet run --project=../api/ &
          API_PID=$!
          ./wait-for-it.sh -t 60 localhost:5000 -- && dotnet test
          kill $API_PID
        env:
          pgconn: ${{ secrets.PG_CONN }}
      
  Deploy-Preview:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Set Up PostgreSQL
        run: |
          export pgconn=${{ secrets.PG_CONN }}

      - name: Build and Deploy
        run: dotnet build --configuration Release --no-restore


