name: Test and run 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - development
    - tests/playwright
#    delete above branch later
  pull_request:
    branches:
    - development
  
env:
    PG_CONN: ${{ secrets.PG_CONN }}
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build and Test
        run: |
          dotnet build
          dotnet test

  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet build
      - name: Ensure browsers are installed
        run: pwsh bin/Debug/net7.0/playwright.ps1 install --with-deps
      - name: Run your tests
        run: dotnet test
      
  Deploy-Preview:
    needs: [test, playwright-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Set Up PostgreSQL
        run: |
          export pgconn=${{ secrets.PG_CONN }}

      - name: Build and Deploy
        run: dotnet build --configuration Release --no-restore


