name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main
  
env:
    AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
    AZURE_WEBAPP_PACKAGE_PATH: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
    DOTNET_VERSION: ${{ secrets.DOTNET_VERSION }}
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore
        run: dotnet restore ./factory-backend.sln
        
      - name: Build
        run: dotnet build ./factory-backend.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./factory-backend.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALSS }}
      
      - name: Deployment 
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package:  ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
        env:
            POSTGRESQLCONNSTR_: ${{ secrets.PG_CONN }}